### ISSUE TITLE
fusermount: if you are sure this is safe, use the 'nonempty' mount option.

### ISSUE THREAD

**Issue by aavileli** [monder/goofys-docker#2]
2017/01/10 02:18:33 Mounting volume binlog-bglcorp-com-au on /var/lib/docker-volumes/goofys/binlog-test-com-au
2017/01/10 02:18:34.434004 s3.ERROR code=incorrect region, the bucket is not in 'eu-west-1' region msg=301 request=

2017/01/10 02:18:34.467775 s3.INFO Switching from region 'eu-west-1' to 'ap-southeast-2'
docker: Error response from daemon: VolumeDriver.Mount: Mount: mount: running fusermount: exit status 1

stderr:
fusermount: mountpoint is not empty
fusermount: if you are sure this is safe, use the 'nonempty' mount option.
See 'docker run --help'.

**Comment by monder** [comment]
Thank you for reporting this. What version of docker and os are you using? Is it a single instance or are you using swarm.
Could you also check whats inside `/var/lib/docker-volumes/goofys/binlog-test-com-au` that's preventing `goofys` to mount there.

**Comment by aavileli** [comment]
Using Docker version 1.11.2, build b9f10c9/1.11.2. There is a file under that directory which I had when it was mounted earlier. I then removed the driver and re-added the driver back again and it started giving me this error

**Comment by aavileli** [comment]
I have removed all the mount directory as docker volume rm does not remove them. Upgraded docker and restarted docker service because it did not show any files in my bucket.
